apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wv1skpia0-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:f1506088db3f877121d5145d487e7b2b7ef5f3cf@sha256:df3addd3c42f3a7e794b4990a036238c8a1d232a7c712d7c92bb95725be29a12
          name: container-image
